// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unhulaavbftqpvflarqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuaHVsYWF2YmZ0cXB2ZmxhcnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTczMDgsImV4cCI6MjA2OTM5MzMwOH0.OYM1Hh8_FuhtKcMyfjPCllxodKQr7ysHwKrrxH6wwL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});